# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a382e7acc4f8a069e3e84a9403d6777b52bb76bbe7b5c6cd31c9767dd27855e549b85249fdab13e89afdd54d19b43218af0d4943492a1616e993a18f57e6e93

test:
  secret_key_base: c07eb1735b1cbf67eedadba6c44cf1b8e9ae26ab807849c8d152645f7c58f7a5bb4dad55078b22b89078aa29ce40bd7f8d8ff7380a211d4c8522e92f5131b7b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
